name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Typescript build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v17
      uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: npm install
      run: npm install
    - name: tsc
      uses: icrawl/action-tsc@v1
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: themikkel/group-dcbot:latest
